import SideBar from '@/components/SideBar'
import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar/>
        <div className='ml-64 w-full md:w-[calc(100%-256px)] bg-gray-50 min-h-screen'>
        {children}
        </div>
        </body>
    </html>
  )
}

